#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-ca-export-cmd() {
  #E Export CockroachDB Certificate Authority public/private keys to directory. 
  #E > NOTE: Private key will be removed from service after export, so you won't be able to add new nodes.
  #E dokku $PLUGIN_COMMAND_PREFIX:ca-export lollipop ./certs/path/ [--force-copy]
  #A service, service to run command against
  #F --force-copy, Don't remove ca.key from service after export
  declare desc="export service CA keys to directory and remove private key from service"
  local cmd="$PLUGIN_COMMAND_PREFIX:ca-export" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" DEST_PATH="$2"
  declare OPT="$3"
  is_implemented_command "$cmd" || dokku_log_fail "Not yet implemented"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  [[ ! -d "$DEST_PATH" ]] && dokku_log_fail "Please specify a valid export directory path for the service certificates"
  verify_service_name "$SERVICE"
  service_ca_export "$SERVICE" "$DEST_PATH" "$OPT"
}

service-ca-export-cmd "$@"
