#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

# TODO: Implement load balancer
service-node-add-cmd() {
  #E Add existing CockroachDB node to cluster load balancer.
  #E > NOTE: All existing service certificates will be removed and regenerated using imported 'ca.key'.
  #E dokku $PLUGIN_COMMAND_PREFIX:ca-import lollipop ./certs/path/
  #A service, service to run command against
  declare desc="import service CA keys ('ca.key' and 'ca.crt') from directory"
  local cmd="$PLUGIN_COMMAND_PREFIX:ca-export" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare NODE_ADDRESS="$2"
  is_implemented_command "$cmd" || dokku_log_fail "Not yet implemented"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  verify_service_name "$SERVICE"
  [[ -z "$NODE_ADDRESS" ]] && dokku_log_fail "Please specify a valid node address to add to service"
  #service_node_add "$1" "$2"
}

service-node-add-cmd "$@"
